[project]
name = 'Renewable-Energy-Microgrid'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consumption-billing]
path = 'contracts/consumption-billing.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-production]
path = 'contracts/energy-production.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-trading]
path = 'contracts/energy-trading.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
